apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecsdemo-nodejs2
  labels:
    app: ecsdemo-nodejs2
  namespace: new-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecsdemo-nodejs2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ecsdemo-nodejs2
    spec:
      containers:
      - image: brentley/ecsdemo-nodejs:latest
        imagePullPolicy: Always
        name: ecsdemo-nodejs2
        ports:
        - containerPort: 3000
          protocol: TCP
